# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
            - python-version: '3.6'
              tox-env: 'mypy'
            - python-version: '3.9'
              tox-env: 'docs'
            - python-version: '3.6'
              tox-env: 'py36'
            - python-version: '3.6'
              tox-env: 'py36-nodeps'
            - python-version: '3.6'
              tox-env: 'py36-extra'
            - python-version: '3.7'
              tox-env: 'py37'
            - python-version: '3.8'
              tox-env: 'py38'
            - python-version: '3.8'
              tox-env: 'py38-nodeps'
            - python-version: '3.9'
              tox-env: 'py39'
            - python-version: '3.9'
              tox-env: 'py39-nodeps'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: tox
      run: |
        tox -e ${{ matrix.tox-env }}
